---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: docs/chem/course
  label: Chem - course
  create: all
  match: "**/*"
- type: directory
  path: docs/chem/IA
  label: Chem - IA
  create: all
  match: "**/*"
- type: directory
  path: docs/chem/topic
  label: Chem - Topic
  create: all
  match: "**/*"
- type: directory
  path: docs/chem/skills
  label: Chem - skills
  create: all
  match: "**/*"
- type: directory
  path: docs/jon
  label: Jon
  create: all
  match: "**/*"
- type: directory
  path: docs/jon/essays
  label: Jon - essays
  create: all
  match: "**/*"
- type: directory
  path: docs/jon/teaching
  label: Jon - teaching
  create: all
  match: "**/*"
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: vuepress build -d .vuepress/dist
  publish_command: vuepress build -d .vuepress/dist
  preview_output_directory: ".vuepress/dist"
  output_directory: ".vuepress/dist"
